spring:
  application:
    name: rmm-service
  datasource:
    url: jdbc:postgresql://localhost:5432/rmm-service
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false
springdoc:
  api-docs:
    path: /api-docs

