create table available_service (id int8 generated by default as identity, description varchar(255), name varchar(255) not null, primary key (id));
create table available_service_pricing_policy (id int8 generated by default as identity, os varchar(255) not null, price int8 not null, available_service_id int8, primary key (id));
create table device (id int8 generated by default as identity, os varchar(255) not null, system_name varchar(255) not null, primary key (id));

alter table if exists available_service add constraint uk_available_service_name unique (name);
alter table if exists available_service_pricing_policy add constraint fk_as_pricing_policy foreign key (available_service_id) references available_service;